(()=>{
'use strict';
const tree=document.getElementById('tree'),canvas=document.getElementById('c');if(!tree||!canvas)return;
const ORDER_KEY='neural-kit:principal-order:v2';let saved=[];try{saved=JSON.parse(localStorage.getItem(ORDER_KEY)||'[]')}catch(_){saved=[]}
let lock=false,drag=null,hold=null,pid=null,start=null,lastY=0,dragNode=null;
const cards=()=>[...tree.children].filter(x=>x.classList?.contains('principalCard')),cid=x=>x?.querySelector(':scope > .treeLine [data-card]')?.dataset.card||'';
const nodeFor=el=>N.find(n=>n.id===cid(el));
function persist(){saved=cards().map(cid).filter(Boolean);localStorage.setItem(ORDER_KEY,JSON.stringify(saved))}
function flipPlace(y){if(!drag)return;const all=cards(),pre=new Map(all.map(x=>[x,x.getBoundingClientRect()])),others=all.filter(x=>x!==drag);let before=null;for(const o of others){const r=o.getBoundingClientRect();if(y<r.top+r.height/2){before=o;break}}before?tree.insertBefore(drag,before):tree.appendChild(drag);requestAnimationFrame(()=>cards().forEach(x=>{if(x===drag)return;const a=pre.get(x),b=x.getBoundingClientRect();if(a&&Math.abs(a.top-b.top)>1)x.animate([{transform:`translateY(${a.top-b.top}px)`},{transform:'translateY(0)'}],{duration:190,easing:'cubic-bezier(.2,.8,.2,1)'})}))}
function apply(){if(lock)return;lock=true;const all=cards(),rank=new Map(saved.map((x,i)=>[x,i]));all.sort((a,b)=>(rank.get(cid(a))??999)-(rank.get(cid(b))??999));all.forEach(x=>tree.appendChild(x));decorateAll();lock=false}
function cancelHold(){if(hold){clearTimeout(hold);hold=null}}
async function setStatus(n,status){if(!n?.uuid)return;const meta={...(n.metadata||{}),lifecycle_changed_at:new Date().toISOString()};const{error}=await sb.from('nodes').update({status,metadata:meta}).eq('id',n.uuid);if(error){alert('No se pudo actualizar la tarjeta.');return}n.status=status;n.metadata=meta;if(status==='archived'||status==='closed'){if(selected===n.id)document.getElementById('detailPanel')?.classList.remove('open');await loadUniverse(currentWorkspace)}else renderTree()}
async function removeNode(n){if(!n?.uuid)return;const kids=N.filter(x=>x.p===n.id);if(kids.length){alert('Esta tarjeta contiene subtarjetas. Muévelas o archiva el universo antes de eliminarlo.');return}if(!confirm(`Eliminar “${n.label}” definitivamente? Esta opción es solo para errores o duplicados.`))return;const{error}=await sb.from('nodes').delete().eq('id',n.uuid);if(error){alert('No se puede eliminar porque tiene historial relacionado. Archívala para conservar la memoria de Neural.');return}await loadUniverse(currentWorkspace)}
function menu(el,n){let m=el.querySelector(':scope > .nkLifeMenu');if(m){m.remove();return}m=document.createElement('div');m.className='nkLifeMenu';m.innerHTML='<button data-life="closed">✓ Finalizar</button><button data-life="archived">◇ Archivar</button><button data-life="delete" class="danger">× Eliminar</button>';el.appendChild(m);m.querySelectorAll('button').forEach(b=>b.onclick=async e=>{e.stopPropagation();m.remove();b.dataset.life==='delete'?await removeNode(n):await setStatus(n,b.dataset.life)});setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!m.contains(e.target))m.remove()},{once:true}),0)}
function validParent(child,parent){if(!child||!parent||child.id===parent.id)return false;let p=parent;while(p){if(p.id===child.id)return false;p=N.find(x=>x.id===p.p)}return true}
async function reparent(child,parent){if(!validParent(child,parent))return;const{error}=await sb.from('nodes').update({parent_id:parent.uuid,color:child.color}).eq('id',child.uuid);if(error)return;child.p=parent.id;child.parentUuid=parent.uuid;expanded.add(parent.id);await loadUniverse(currentWorkspace);expanded.add(parent.id);renderTree()}
function hierarchyTarget(x,y){const els=[...document.elementsFromPoint(x,y)];const row=els.find(e=>e?.matches?.('[data-card]'));return row?N.find(n=>n.id===row.dataset.card):null}
function decorateCard(el){const line=el.querySelector(':scope > .treeLine'),row=line?.querySelector(':scope > .treeRow'),n=nodeFor(el);if(!line||!row||!n)return;let tools=line.querySelector('.nkTools');if(!tools){tools=document.createElement('div');tools.className='nkTools';const hasKids=!!el.querySelector(':scope > .branch');tools.innerHTML=`${hasKids?'<button class="nkFold" title="Desplegar / contraer">⌄</button>':''}<button class="nkTag" title="Agregar etiqueta">◈</button><button class="nkMore" title="Finalizar, archivar o eliminar">•••</button>`;line.appendChild(tools);tools.querySelector('.nkFold')?.addEventListener('click',e=>{e.stopPropagation();const branch=el.querySelector(':scope > .branch');if(!branch)return;const opening=branch.classList.contains('collapsed');branch.classList.toggle('collapsed',!opening);e.currentTarget.textContent=opening?'⌃':'⌄';opening?expanded.add(n.id):expanded.delete(n.id)});tools.querySelector('.nkMore')?.addEventListener('click',e=>{e.stopPropagation();menu(el,n)});tools.querySelector('.nkTag')?.addEventListener('click',e=>{e.stopPropagation();row.animate([{boxShadow:'0 0 0 transparent'},{boxShadow:`0 0 18px ${n.color}55`},{boxShadow:'0 0 0 transparent'}],{duration:450})})}
 if(el.dataset.dragV6)return;el.dataset.dragV6='1';row.style.touchAction='pan-y';row.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;cancelHold();pid=e.pointerId;start={x:e.clientX,y:e.clientY};lastY=e.clientY;dragNode=n;hold=setTimeout(()=>{drag=el;el.classList.add('nkDragging');document.body.classList.add('nkHierarchyDrag');row.style.touchAction='none';try{row.setPointerCapture(e.pointerId)}catch(_){ }navigator.vibrate?.(15)},210)});row.addEventListener('pointermove',e=>{if(pid!==e.pointerId)return;if(!drag){if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>9)cancelHold();return}e.preventDefault();if(el.classList.contains('principalCard')&&Math.abs(e.clientY-lastY)>3){lastY=e.clientY;flipPlace(e.clientY)}const t=hierarchyTarget(e.clientX,e.clientY);document.querySelectorAll('.nkDropTarget').forEach(x=>x.classList.remove('nkDropTarget'));if(t&&validParent(dragNode,t))document.querySelector(`[data-card="${CSS.escape(t.id)}"]`)?.closest('.treeLine')?.classList.add('nkDropTarget')});const end=async e=>{if(pid!==e.pointerId)return;cancelHold();if(drag){e.preventDefault();e.stopImmediatePropagation();const target=hierarchyTarget(e.clientX,e.clientY);document.querySelectorAll('.nkDropTarget').forEach(x=>x.classList.remove('nkDropTarget'));if(target&&validParent(dragNode,target)&&target.id!==dragNode.p)await reparent(dragNode,target);else if(el.classList.contains('principalCard'))persist();drag.classList.remove('nkDragging');document.body.classList.remove('nkHierarchyDrag');row.style.touchAction='pan-y'}drag=null;dragNode=null;pid=null;start=null};row.addEventListener('pointerup',end,true);row.addEventListener('pointercancel',end,true)}
function decorateAll(){document.querySelectorAll('.nodeCard').forEach(decorateCard)}
const st=document.createElement('style');st.textContent=`.principalCard>.treeLine>.treeRow:before,.nodeCard>.treeLine>.treeRow:before{content:'☷';position:absolute;left:4px;top:50%;transform:translateY(-50%);font-size:15px;font-weight:800;color:rgba(255,255,255,.48);text-shadow:0 0 10px rgba(255,255,255,.18)}.nodeCard>.treeLine>.treeRow{padding-left:23px!important}.principalCard>.treeLine>.treeRow{padding-right:104px!important}.nkDragging{opacity:.8;z-index:100;filter:drop-shadow(0 16px 30px rgba(0,0,0,.55))}.nkDropTarget>.treeRow{border-color:rgba(255,255,255,.42)!important;box-shadow:0 0 20px rgba(255,255,255,.12),inset 0 0 16px rgba(255,255,255,.05)!important}.nkTools{position:absolute;right:35px;top:50%;transform:translateY(-50%);display:flex;gap:3px;z-index:9}.nkTools button{width:23px;height:23px;border:1px solid rgba(255,255,255,.08);border-radius:7px;background:rgba(255,255,255,.03);color:rgba(255,255,255,.48);font-size:10px}.nkTools button:hover{color:#fff;background:rgba(255,255,255,.09)}.nkLifeMenu{position:absolute;right:5px;top:42px;z-index:120;width:138px;padding:5px;border:1px solid rgba(255,255,255,.1);border-radius:11px;background:rgba(8,10,14,.96);backdrop-filter:blur(18px);box-shadow:0 14px 30px rgba(0,0,0,.45)}.nkLifeMenu button{display:block;width:100%;padding:8px;border:0;background:transparent;color:#c8cdd4;text-align:left;font-size:9px;border-radius:7px}.nkLifeMenu button:hover{background:rgba(255,255,255,.07);color:#fff}.nkLifeMenu .danger{color:#e99a9a}.addCard{opacity:.58!important}.principalCard>.treeLine>.expandMark{display:none!important}`;document.head.appendChild(st);new MutationObserver(()=>requestAnimationFrame(()=>{apply();decorateAll()})).observe(tree,{childList:true,subtree:true});setTimeout(()=>{apply();decorateAll()},120);

// Hide archived/closed nodes from the active navigation after each universe load.
const baseLoad=loadUniverse;loadUniverse=async function(ws){await baseLoad(ws);const hidden=N.filter(n=>n.status==='archived'||n.status==='closed');if(hidden.length){const ids=new Set(hidden.map(n=>n.id));N=N.filter(n=>!ids.has(n.id));L=L.filter(([a,b])=>!ids.has(a)&&!ids.has(b))}renderTree();decorateAll()};

const panel=document.getElementById('detailPanel'),closeDetail=()=>panel?.classList.remove('open'),selectV6=selectNode;selectNode=function(n,open){closeDetail();selectV6(n,open)};canvas.addEventListener('pointerdown',closeDetail,true);['saveTask','saveColor'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(closeDetail,120)));

// Keep V5 semantic pinch-out: focused universe -> global overview after deliberate zoom-out release.
const pts=new Map();let one=null,pinch=null;const vals=()=>[...pts.values()];function sync(){pointers.clear();for(const[id,p]of pts)pointers.set(id,p)}function beginPinch(){const a=vals();if(a.length!==2)return;const cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(24,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y));pinch={d,cx,cy,z:zoom,px:panX,py:panY,cz:camZ,focused:!!activeUniverse,min:1};one=null;focusTarget=null}
function overview(){activeUniverse=null;selected=null;focusGlow=0;closeDetail();expanded.clear();renderTree();document.getElementById('universeBadge')?.classList.remove('on');focusTarget={zoom:.72,panX:0,panY:0,camZ:0}}
canvas.onpointerdown=e=>{closeDetail();canvas.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});sync();focusTarget=null;if(pts.size===1)one={sx:e.clientX,sy:e.clientY,lastT:performance.now(),time:performance.now(),moved:false};else if(pts.size===2)beginPinch()};canvas.onpointermove=e=>{if(!pts.has(e.pointerId))return;const prev=pts.get(e.pointerId),now=performance.now();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});sync();if(pts.size===1&&one){const dx=e.clientX-prev.x,dy=e.clientY-prev.y,dt=Math.max(8,now-one.lastT);rot+=dx*.006;tilt=Math.max(-.82,Math.min(.82,tilt+dy*.003));rotV=rotV*.55+dx*.006*(16.67/dt)*.45;tiltV=tiltV*.58+dy*.003*(16.67/dt)*.42;one.lastT=now;if(Math.hypot(e.clientX-one.sx,e.clientY-one.sy)>7)one.moved=true;return}if(pts.size===2&&pinch){const a=vals(),cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(24,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)),ratio=d/pinch.d;pinch.min=Math.min(pinch.min,ratio);const nz=Math.max(.28,Math.min(5.2,pinch.z*ratio)),centerX=sideW()+(W-sideW())/2,centerY=H*.46,k=nz/pinch.z;zoom=nz;camZ=pinch.cz;panX=(pinch.cx-centerX)-(pinch.cx-centerX-pinch.px)*k+(cx-pinch.cx);panY=(pinch.cy-centerY)-(pinch.cy-centerY-pinch.py)*k+(cy-pinch.cy)}};function finish(e){const p=pinch,click=pts.size===1&&one&&!one.moved&&performance.now()-one.time<350;pts.delete(e.pointerId);sync();if(click){const h=[...hit].sort((a,b)=>b.z-a.z).find(o=>Math.hypot(e.clientX-o.x,e.clientY-o.y)<o.r);if(h)selectNode(h.n,true)}if(pts.size===1){const q=vals()[0];one={sx:q.x,sy:q.y,lastT:performance.now(),time:performance.now(),moved:false};pinch=p}else if(!pts.size){one=null;pinch=null;if(p?.focused&&p.min<.70)overview()}}canvas.onpointerup=finish;canvas.onpointercancel=finish;
const hint=document.querySelector('.hint');if(hint)hint.textContent='☷ mantén y arrastra · suelta sobre otra tarjeta para cambiar jerarquía · ••• archivar';
})();