(()=>{
'use strict';
const tree=document.getElementById('tree'),canvas=document.getElementById('c');if(!tree||!canvas)return;

// V5 — fluid priority sorting, explicit card controls, ephemeral detail, semantic pinch-out.
const ORDER_KEY='neural-kit:principal-order:v2';let saved=[];try{saved=JSON.parse(localStorage.getItem(ORDER_KEY)||'[]')}catch(_){saved=[]}
let lock=false,drag=null,hold=null,pid=null,start=null,lastY=0;
const cards=()=>[...tree.children].filter(x=>x.classList?.contains('principalCard')),cid=x=>x?.querySelector(':scope > .treeLine [data-card]')?.dataset.card||'';
function persist(){saved=cards().map(cid).filter(Boolean);localStorage.setItem(ORDER_KEY,JSON.stringify(saved))}
function flipPlace(y){if(!drag)return;const all=cards(),beforeRects=new Map(all.map(x=>[x,x.getBoundingClientRect()]));const others=all.filter(x=>x!==drag);let before=null;for(const o of others){const r=o.getBoundingClientRect();if(y<r.top+r.height/2){before=o;break}}before?tree.insertBefore(drag,before):tree.appendChild(drag);requestAnimationFrame(()=>{for(const x of cards()){if(x===drag)continue;const a=beforeRects.get(x),b=x.getBoundingClientRect();if(!a)continue;const dy=a.top-b.top;if(Math.abs(dy)>1){x.animate([{transform:`translateY(${dy}px)`},{transform:'translateY(0)'}],{duration:180,easing:'cubic-bezier(.2,.8,.2,1)'})}}})}
function apply(){if(lock)return;lock=true;const all=cards(),rank=new Map(saved.map((x,i)=>[x,i]));all.sort((a,b)=>(rank.get(cid(a))??999)-(rank.get(cid(b))??999));all.forEach(x=>tree.appendChild(x));decorate();lock=false}
function cancelHold(){if(hold){clearTimeout(hold);hold=null}}
function decorate(){cards().forEach(el=>{const line=el.querySelector(':scope > .treeLine'),row=line?.querySelector(':scope > .treeRow');if(!line||!row)return;let tools=line.querySelector('.nkTools');if(!tools){tools=document.createElement('div');tools.className='nkTools';const hasKids=!!el.querySelector(':scope > .branch');tools.innerHTML=`${hasKids?'<button class="nkFold" title="Desplegar / contraer" aria-label="Desplegar o contraer">⌄</button>':''}<button class="nkTag" title="Agregar etiqueta" aria-label="Agregar etiqueta">◈</button>`;line.appendChild(tools);tools.querySelector('.nkFold')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const branch=el.querySelector(':scope > .branch'),id=cid(el);if(!branch)return;const opening=branch.classList.contains('collapsed');branch.classList.toggle('collapsed',!opening);const b=e.currentTarget;b.textContent=opening?'⌃':'⌄';b.title=opening?'Contraer':'Desplegar';if(typeof expanded!=='undefined'){opening?expanded.add(id):expanded.delete(id)}});tools.querySelector('.nkTag')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const row=el.querySelector(':scope > .treeLine > .treeRow');row?.animate([{boxShadow:'0 0 0 rgba(255,255,255,0)'},{boxShadow:'0 0 18px rgba(255,255,255,.18)'},{boxShadow:'0 0 0 rgba(255,255,255,0)'}],{duration:420});const plus=line.querySelector('.addCard');if(plus)plus.title='Agregar tarjeta';});}
 if(el.dataset.sortV5)return;el.dataset.sortV5='1';row.style.touchAction='pan-y';row.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;cancelHold();pid=e.pointerId;start={x:e.clientX,y:e.clientY};lastY=e.clientY;hold=setTimeout(()=>{drag=el;el.classList.add('nkDragging');row.style.touchAction='none';try{row.setPointerCapture(e.pointerId)}catch(_){ }navigator.vibrate?.(15)},210)});row.addEventListener('pointermove',e=>{if(pid!==e.pointerId)return;if(!drag){if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>9)cancelHold();return}e.preventDefault();if(Math.abs(e.clientY-lastY)>3){lastY=e.clientY;flipPlace(e.clientY)}});const end=e=>{if(pid!==e.pointerId)return;cancelHold();if(drag){e.preventDefault();e.stopImmediatePropagation();persist();drag.classList.remove('nkDragging');row.style.touchAction='pan-y';el.animate([{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:170,easing:'ease-out'})}drag=null;pid=null;start=null};row.addEventListener('pointerup',end,true);row.addEventListener('pointercancel',end,true)})}
const st=document.createElement('style');st.textContent=`
.principalCard{position:relative;transition:opacity .16s ease}.principalCard.nkDragging{opacity:.82;z-index:90;filter:drop-shadow(0 16px 28px rgba(0,0,0,.5))}.principalCard>.treeLine>.treeRow:before{content:'☷';position:absolute;left:4px;top:50%;transform:translateY(-50%);font-size:15px;font-weight:700;color:rgba(255,255,255,.42);text-shadow:0 0 10px rgba(255,255,255,.14)}.principalCard.nkDragging>.treeLine>.treeRow:before{color:#fff}.principalCard>.treeLine>.treeRow{padding-left:23px!important;padding-right:78px!important}.nkTools{position:absolute;right:36px;top:50%;transform:translateY(-50%);display:flex;gap:3px;z-index:7}.nkTools button{width:24px;height:24px;border:1px solid rgba(255,255,255,.07);border-radius:7px;background:rgba(255,255,255,.025);color:rgba(255,255,255,.43);font-size:11px;backdrop-filter:blur(8px)}.nkTools button:hover{color:#fff;background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.16)}.addCard{opacity:.55!important}.addCard:hover{opacity:1!important}.principalCard>.treeLine>.expandMark{display:none!important}
`;document.head.appendChild(st);new MutationObserver(()=>requestAnimationFrame(apply)).observe(tree,{childList:true,subtree:false});setTimeout(apply,100);

// Detail is a temporary layer.
const panel=document.getElementById('detailPanel');const closeDetail=()=>panel?.classList.remove('open');const selectV5=selectNode;selectNode=function(n,open){closeDetail();selectV5(n,open)};canvas.addEventListener('pointerdown',closeDetail,true);document.getElementById('resetUniverse')?.addEventListener('click',closeDetail,true);['saveTask','saveColor'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(closeDetail,120)));

// Pinch: continuous while touching. A deliberate pinch-out from a focused universe returns to global only AFTER release.
const pts=new Map();let one=null,pinch=null;const vals=()=>[...pts.values()];function sync(){pointers.clear();for(const[id,p]of pts)pointers.set(id,p)}
function beginPinch(){const a=vals();if(a.length!==2)return;const cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(24,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y));pinch={d,cx,cy,z:zoom,px:panX,py:panY,cz:camZ,focused:!!activeUniverse,min:1};one=null;focusTarget=null;rotV*=.2;tiltV*=.2}
function overview(){activeUniverse=null;selected=null;focusGlow=0;closeDetail();expanded.clear();renderTree();document.getElementById('universeBadge')?.classList.remove('on');focusTarget={zoom:.72,panX:0,panY:0,camZ:0}}
canvas.onpointerdown=e=>{closeDetail();canvas.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});sync();focusTarget=null;if(pts.size===1)one={sx:e.clientX,sy:e.clientY,lastT:performance.now(),time:performance.now(),moved:false};else if(pts.size===2)beginPinch()};
canvas.onpointermove=e=>{if(!pts.has(e.pointerId))return;const prev=pts.get(e.pointerId),now=performance.now();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});sync();if(pts.size===1&&one){const dx=e.clientX-prev.x,dy=e.clientY-prev.y,dt=Math.max(8,now-one.lastT);rot+=dx*.006;tilt=Math.max(-.82,Math.min(.82,tilt+dy*.003));rotV=rotV*.55+dx*.006*(16.67/dt)*.45;tiltV=tiltV*.58+dy*.003*(16.67/dt)*.42;one.lastT=now;if(Math.hypot(e.clientX-one.sx,e.clientY-one.sy)>7)one.moved=true;return}if(pts.size===2&&pinch){const a=vals(),cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(24,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)),ratio=d/pinch.d;pinch.min=Math.min(pinch.min,ratio);const nz=Math.max(.28,Math.min(5.2,pinch.z*ratio)),centerX=sideW()+(W-sideW())/2,centerY=H*.46,k=nz/pinch.z;zoom=nz;camZ=pinch.cz;panX=(pinch.cx-centerX)-(pinch.cx-centerX-pinch.px)*k+(cx-pinch.cx);panY=(pinch.cy-centerY)-(pinch.cy-centerY-pinch.py)*k+(cy-pinch.cy)}};
function finish(e){const p=pinch,click=pts.size===1&&one&&!one.moved&&performance.now()-one.time<350;pts.delete(e.pointerId);sync();if(click){const h=[...hit].sort((a,b)=>b.z-a.z).find(o=>Math.hypot(e.clientX-o.x,e.clientY-o.y)<o.r);if(h)selectNode(h.n,true)}if(pts.size===1){const q=vals()[0];one={sx:q.x,sy:q.y,lastT:performance.now(),time:performance.now(),moved:false};pinch=p}else if(!pts.size){one=null;pinch=null;if(p?.focused&&p.min<.70)overview()}}
canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onwheel=e=>{e.preventDefault();closeDetail();const old=zoom,nz=Math.max(.28,Math.min(5.2,old*Math.exp(-e.deltaY*.0012))),cx=e.clientX,cy=e.clientY,centerX=sideW()+(W-sideW())/2,centerY=H*.46,k=nz/old;zoom=nz;panX=(cx-centerX)-(cx-centerX-panX)*k;panY=(cy-centerY)-(cy-centerY-panY)*k};
const hint=document.querySelector('.hint');if(hint)hint.textContent='☷ mantén y arrastra · ⌄ despliega · + tarjeta · pellizca hacia afuera para volver';
})();