(()=>{
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/×/g,'x');
const clearTaskEditor=()=>['taskTitle','taskDescription','taskDue','taskReminder'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});
const oldRenderDetail=renderDetail;renderDetail=function(n){oldRenderDetail(n);let scope=document.getElementById('taskScope'),editor=document.querySelector('#detailPanel .editor');if(editor){if(!scope){scope=document.createElement('div');scope.id='taskScope';scope.style.cssText='font-size:9px;color:#9aa1aa;margin:3px 0 1px;letter-spacing:.04em';editor.parentNode.insertBefore(scope,editor)}scope.textContent='TAREAS DE · '+n.label;const title=document.getElementById('taskTitle');if(title)title.placeholder='Nueva tarea para '+n.label}};
const oldSelectNode=selectNode;selectNode=function(n,open){clearTaskEditor();oldSelectNode(n,open)};
function findNodeByMention(text){const s=norm(text);let best=null;for(const n of N){const l=norm(n.label);if(l.length>2&&s.includes(l)&&(!best||l.length>norm(best.label).length))best=n}return best}
function findParentFromText(text){const s=norm(text),aliases=[['gala',n=>norm(n.label).includes('gala')],['brava',n=>norm(n.label)==='brava'],['think',n=>norm(n.label)==='think'],['ventas',n=>norm(n.label)==='ventas'],['cuerpo',n=>norm(n.label)==='cuerpo']];for(const[word,test]of aliases)if(s.includes(word)){const n=N.find(test);if(n)return n}return null}
function extractProspectName(text){let m=text.match(/(?:se\s+llama|llamado|llamada)\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9][A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9 .&_-]{1,34}?)(?=\s+(?:es|para|que|y\s+es|una|un)\b|[,.]|$)/i);return m?m[1].trim().replace(/[.,]+$/,''):null}
async function ensureProspect(text){const s=norm(text);if(!/(nuevo\s+prospecto|prospecto\s+nuevo|cliente\s+nuevo)/.test(s))return null;const name=extractProspectName(text);if(!name)return null;const existing=N.find(n=>norm(n.label)===norm(name));if(existing)return existing;const parent=findParentFromText(text)||N.find(n=>norm(n.label)==='ventas')||coreNode();const{data,error}=await sb.from('nodes').insert({workspace_id:currentWorkspace.id,node_key:'AUTO_'+Date.now(),label:name,node_type:'prospect',parent_id:parent?.uuid||null,color:parent?.color||'#FF8B8B',status:'prospect',importance:3,metadata:{source:'composer',auto_created:true}}).select().single();if(error||!data)return null;const obj={id:data.node_key,label:data.label,r:4.8,parentUuid:data.parent_id,uuid:data.id,color:data.color||parent?.color||'#FF8B8B',type:data.node_type,phase:Math.random()*6.28,order:N.length,p:parent?.id||null};N.push(obj);if(parent)L.push([parent.id,obj.id]);renderTree();return obj}

// SIDEBAR V2 — only principal universes visible on load; descendants reveal on demand.
const sideStyle=document.createElement('style');sideStyle.textContent=`
.sidebar{background:linear-gradient(180deg,rgba(5,7,10,.84),rgba(3,5,8,.92));}
#tree{display:grid;gap:7px}.treeLine{position:relative;display:grid!important;grid-template-columns:1fr!important;gap:0!important;align-items:center}.treeLine>.twist{display:none!important}.treeLine>.plus{display:none!important}
.treeRow{position:relative!important;min-height:48px!important;padding:9px 11px!important;border:1px solid rgba(255,255,255,.075)!important;border-radius:14px!important;background:linear-gradient(135deg,rgba(255,255,255,.052),rgba(255,255,255,.014))!important;backdrop-filter:blur(18px);box-shadow:inset 0 1px 0 rgba(255,255,255,.045),0 10px 28px rgba(0,0,0,.18);transition:.18s ease}
.treeRow:hover,.treeRow.active{transform:translateX(2px);border-color:rgba(255,255,255,.15)!important;background:linear-gradient(135deg,rgba(255,255,255,.085),rgba(255,255,255,.025))!important}
.treeRow .dot{width:18px!important;height:18px!important;border-radius:6px!important;margin-top:0!important;box-shadow:0 0 18px currentColor,inset 0 1px 0 rgba(255,255,255,.55)!important;opacity:.9}.treeRow b{font-size:10px!important;letter-spacing:.045em}.treeRow span{font-size:7px!important;opacity:.55}.branch{margin:5px 0 3px 14px!important;padding:0 0 0 8px!important;border-left:1px solid rgba(255,255,255,.07)!important;display:grid;gap:4px}.branch.collapsed{display:none!important}.branch .treeRow{min-height:38px!important;border-radius:11px!important;padding:7px 9px!important;background:rgba(255,255,255,.018)!important}.branch .treeRow .dot{width:10px!important;height:10px!important;border-radius:3px!important}.branch .branch .treeRow{opacity:.88}
.addCard{position:absolute;right:7px;top:50%;transform:translateY(-50%);z-index:4;width:25px;height:25px;border:1px solid rgba(255,255,255,.08);border-radius:8px;background:rgba(255,255,255,.025);color:#7d848e;font-size:15px;line-height:20px;opacity:0;transition:.16s}.treeLine:hover>.addCard,.treeLine:focus-within>.addCard{opacity:1}.addCard:hover{color:#fff;border-color:rgba(255,255,255,.18);background:rgba(255,255,255,.07)}
.expandMark{position:absolute;right:38px;top:50%;transform:translateY(-50%);font-size:8px;color:#707781;pointer-events:none}.quickAdd{margin:5px 0 7px 14px!important}.quickAdd:before{content:'AGREGAR TARJETA';display:block;font-size:7px;color:#69717c;letter-spacing:.1em;position:absolute;margin-top:-11px}.sideTitle{margin-top:17px}
`;document.head.appendChild(sideStyle);
function isPrincipal(n){const core=coreNode();return !!core&&n.p===core.id}
function cardTree(parent,q=''){let kids=N.filter(n=>(n.p||null)===(parent||null));return kids.map(n=>{const descendants=childrenOf(n.id),match=!q||norm(n.label).includes(q)||norm(pathFor(n)).includes(q),child=cardTree(n.id,q),show=match||child;if(!show)return'';const open=expanded.has(n.id)||!!q,principal=isPrincipal(n),hasKids=descendants.length>0;return`<div class="nodeCard ${principal?'principalCard':''}"><div class="treeLine"><button class="treeRow ${selected===n.id?'active':''}" data-card="${n.id}"><i class="dot" style="background:${n.color};color:${n.color}"></i><div><b>${esc(n.label)}</b><span>${principal?(hasKids?descendants.length+' conexiones':'universo'):esc(pathFor(n))}</span></div></button>${hasKids?`<span class="expandMark">${open?'▾':'▸'}</span>`:''}<button class="addCard" data-addcard="${n.id}" title="Agregar tarjeta">+</button></div>${quickAdd.has(n.id)?`<div class="quickAdd"><input data-addinput="${n.id}" placeholder="Nombre de tarjeta"><button data-saveadd="${n.id}">✓</button></div>`:''}${child?`<div class="branch ${open?'':'collapsed'}">${child}</div>`:''}</div>`}).join('')}
function renderSidebarV2(){if(!N.length)return;const core=coreNode(),q=norm(document.getElementById('searchInput').value.trim());let roots=core?[core]:N.filter(n=>!n.p);let html='';if(core){html=childrenOf(core.id).map(n=>{const descendants=childrenOf(n.id),match=!q||norm(n.label).includes(q)||norm(pathFor(n)).includes(q)||cardTree(n.id,q),child=cardTree(n.id,q);if(q&&!match&&!child)return'';const open=expanded.has(n.id)||!!q;return`<div class="nodeCard principalCard"><div class="treeLine"><button class="treeRow ${selected===n.id?'active':''}" data-card="${n.id}"><i class="dot" style="background:${n.color};color:${n.color}"></i><div><b>${esc(n.label)}</b><span>${descendants.length?descendants.length+' conexiones':'universo'}</span></div></button>${descendants.length?`<span class="expandMark">${open?'▾':'▸'}</span>`:''}<button class="addCard" data-addcard="${n.id}" title="Agregar tarjeta">+</button></div>${quickAdd.has(n.id)?`<div class="quickAdd"><input data-addinput="${n.id}" placeholder="Nombre de tarjeta"><button data-saveadd="${n.id}">✓</button></div>`:''}${child?`<div class="branch ${open?'':'collapsed'}">${child}</div>`:''}</div>`}).join('')}else html=cardTree(null,q);document.getElementById('tree').innerHTML=html||'<div class="reminder">Sin resultados</div>';
 const tree=document.getElementById('tree');tree.querySelectorAll('[data-card]').forEach(b=>b.onclick=e=>{const n=N.find(x=>x.id===b.dataset.card);if(!n)return;if(childrenOf(n.id).length){expanded.has(n.id)?expanded.delete(n.id):expanded.add(n.id)}selectNode(n,true);renderSidebarV2()});tree.querySelectorAll('[data-addcard]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.addcard;quickAdd.has(id)?quickAdd.delete(id):quickAdd.add(id);renderSidebarV2()});tree.querySelectorAll('[data-saveadd]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const parent=N.find(n=>n.id===b.dataset.saveadd),inp=tree.querySelector(`[data-addinput="${b.dataset.saveadd}"]`),label=inp?.value.trim();if(!parent||!label)return;const{data,error}=await sb.from('nodes').insert({workspace_id:currentWorkspace.id,node_key:'USER_'+Date.now(),label,node_type:'project',parent_id:parent.uuid,color:parent.color,status:'active',importance:3}).select().single();if(!error){N.push({id:data.node_key,label:data.label,r:4.8,parentUuid:data.parent_id,uuid:data.id,color:data.color,type:data.node_type,phase:Math.random()*6.28,order:N.length,p:parent.id});L.push([parent.id,data.node_key]);quickAdd.delete(parent.id);expanded.add(parent.id);renderSidebarV2()}})}
const originalRenderTree=renderTree;renderTree=renderSidebarV2;const search=document.getElementById('searchInput');search.oninput=renderSidebarV2;
// Start truly collapsed every session. Principal universes only.
expanded.clear();setTimeout(()=>{expanded.clear();renderSidebarV2()},60);

// HOY
let todayBox=null;function ensureTodayUI(){if(todayBox)return;todayBox=document.createElement('div');todayBox.id='neuralToday';todayBox.style.cssText='position:fixed;z-index:8;left:calc(var(--side) + 20px);top:118px;width:min(330px,calc(100vw - var(--side) - 40px));padding:11px;border:1px solid rgba(255,255,255,.09);border-radius:16px;background:rgba(6,8,11,.76);backdrop-filter:blur(20px);font-size:9px;color:#b7bdc6';todayBox.innerHTML='<b style="color:#fff;letter-spacing:.12em">HOY · NEURAL</b><div id="neuralTodayList" style="margin-top:7px">Calculando dirección…</div>';document.body.appendChild(todayBox)}
async function loadToday(){if(!currentWorkspace)return;ensureTodayUI();const{data,error}=await sb.rpc('neural_today',{p_workspace_id:currentWorkspace.id});const list=document.getElementById('neuralTodayList');if(!list)return;if(error){list.textContent='Motor Neural preparando contexto.';return}list.innerHTML=(data||[]).map((x,i)=>`<div style="padding:7px 0;border-top:${i?'1px solid rgba(255,255,255,.06)':'0'}"><span style="color:#6f7680">${i+1} · ${esc(x.node_label||'NEURAL')}</span><div style="color:#f2f2ef;margin-top:2px;line-height:1.3">${esc(x.title)}</div></div>`).join('')||'Sin intervención prioritaria. Registra qué pasó hoy.'}
const oldLoadUniverse=loadUniverse;loadUniverse=async function(ws){await oldLoadUniverse(ws);expanded.clear();renderSidebarV2();await loadToday()};
document.getElementById('send').onclick=async()=>{const note=document.getElementById('note'),text=note.value.trim();if(!text||!currentWorkspace)return;let n=await ensureProspect(text);if(!n)n=findNodeByMention(text)||findParentFromText(text)||coreNode()||N[0];const am=amount(text);const{data,error}=await sb.from('events').insert({workspace_id:currentWorkspace.id,node_id:n?.uuid||null,event_type:'note',raw_text:text,amount:am,currency:'MXN',source:'web'}).select().single();if(!error){E.unshift(data);const{data:brain}=await sb.rpc('neural_process_event',{p_workspace_id:currentWorkspace.id,p_node_id:n?.uuid||null,p_text:text,p_amount:am});note.value='';route.textContent='→ '+pathFor(n)+(brain?.stage?' · '+String(brain.stage).replace('_',' '):'');renderEvents();if(selected===n.id)renderDetail(n);await loadToday()}};

// Gestures: preserve semantic pinch, decide scale only on release.
const oldBasePosition=basePosition;basePosition=function(n){const p=oldBasePosition(n),d=depth(n);if(activeUniverse){const u=N.find(x=>x.id===activeUniverse);if(u&&isDescendantOrSelf(n,activeUniverse)){const uc=oldBasePosition(u),dx=p.x-uc.x,dz=p.z-uc.z,a=rot*.9,ca=Math.cos(a),sa=Math.sin(a);return{x:uc.x+dx*ca-dz*sa,y:p.y,z:uc.z+dx*sa+dz*ca}}}if(d<=1){const a=rot*.35,ca=Math.cos(a),sa=Math.sin(a);return{x:p.x*ca-p.z*sa,y:p.y,z:p.x*sa+p.z*ca}}return p};
let gSingle=null,gPinch=null;const gVals=()=>[...pointers.values()];function globalOverview(animated=true){activeUniverse=null;selected=null;focusGlow=0;document.getElementById('universeBadge')?.classList.remove('on');document.getElementById('detailPanel')?.classList.remove('open');expanded.clear();renderSidebarV2();if(animated)focusTarget={zoom:.72,panX:0,panY:0,camZ:0};else{focusTarget=null;zoom=.72;camZ=0;panX=0;panY=0}}function nearestUniverseAt(x,y,maxDist=260){let best=null,bestD=maxDist;for(const n of rootGroups()){const p=project(basePosition(n)),d=Math.hypot(x-p.x,y-p.y);if(d<bestD){best=n;bestD=d}}return best}function enterByPinch(n){if(!n)return;selected=n.id;expanded.add(n.id);renderSidebarV2();renderDetail(n);focusOn(n);document.getElementById('detailPanel')?.classList.remove('open')}
C.onpointerdown=e=>{C.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});focusTarget=null;if(pointers.size===1){gSingle={sx:e.clientX,sy:e.clientY,lastT:performance.now(),time:performance.now(),moved:false};gPinch=null}else if(pointers.size===2){const a=gVals(),cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(20,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y));gPinch={d,cx,cy,lastCx:cx,lastCy:cy,zoom,camZ,panX,panY,startedUniverse:!!activeUniverse,minRatio:1,maxRatio:1};gSingle=null;rotV*=.35;tiltV*=.35}};
C.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),now=performance.now();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&gSingle){const dx=e.clientX-old.x,dy=e.clientY-old.y,dt=Math.max(8,now-gSingle.lastT);rot+=dx*.006;tilt=Math.max(-.82,Math.min(.82,tilt+dy*.003));rotV=rotV*.55+dx*.006*(16.67/dt)*.45;tiltV=tiltV*.58+dy*.003*(16.67/dt)*.42;gSingle.lastT=now;if(Math.hypot(e.clientX-gSingle.sx,e.clientY-gSingle.sy)>7)gSingle.moved=true}else if(pointers.size===2&&gPinch){const a=gVals(),cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2,d=Math.max(20,Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)),ratio=d/gPinch.d;gPinch.lastCx=cx;gPinch.lastCy=cy;gPinch.minRatio=Math.min(gPinch.minRatio,ratio);gPinch.maxRatio=Math.max(gPinch.maxRatio,ratio);const newZoom=Math.max(.30,Math.min(4.8,gPinch.zoom*ratio)),centerX=sideW()+(W-sideW())/2,centerY=H*.46,scaleFactor=newZoom/gPinch.zoom;zoom=newZoom;camZ=gPinch.camZ;panX=(gPinch.cx-centerX)-(gPinch.cx-centerX-gPinch.panX)*scaleFactor+(cx-gPinch.cx);panY=(gPinch.cy-centerY)-(gPinch.cy-centerY-gPinch.panY)*scaleFactor+(cy-gPinch.cy)}};
function finishGesture(e){const one=gSingle,pinch=gPinch,click=pointers.size===1&&one&&!one.moved&&performance.now()-one.time<350;pointers.delete(e.pointerId);if(click){const h=[...hit].sort((a,b)=>b.z-a.z).find(o=>Math.hypot(e.clientX-o.x,e.clientY-o.y)<o.r);if(h)selectNode(h.n,true)}if(pointers.size===1){const q=gVals()[0];gSingle={sx:q.x,sy:q.y,lastT:performance.now(),time:performance.now(),moved:false};gPinch=null}else if(!pointers.size){gSingle=null;gPinch=null;if(!pinch){if(activeUniverse)constrainActiveView();return}if(pinch.startedUniverse&&pinch.minRatio<.64){globalOverview(true);return}if(!activeUniverse&&pinch.maxRatio>1.28&&zoom>1){const target=nearestUniverseAt(pinch.lastCx,pinch.lastCy);if(target){enterByPinch(target);return}}if(!activeUniverse&&zoom<.5)globalOverview(true);else if(activeUniverse)constrainActiveView()}}C.onpointerup=finishGesture;C.onpointercancel=finishGesture;C.onwheel=e=>{e.preventDefault();zoom=Math.max(.3,Math.min(4.8,zoom*Math.exp(-e.deltaY*.0012)));if(!activeUniverse&&zoom<.5)globalOverview(true)};
let throwState=null;C.addEventListener('pointerdown',e=>{if(pointers.size<=1)throwState={x:e.clientX,y:e.clientY,t:performance.now(),vx:0,vy:0}},true);C.addEventListener('pointermove',e=>{if(!throwState||pointers.size>1)return;const now=performance.now(),dt=Math.max(8,now-throwState.t),dx=e.clientX-throwState.x,dy=e.clientY-throwState.y;throwState.vx=throwState.vx*.55+(dx/dt)*.45;throwState.vy=throwState.vy*.55+(dy/dt)*.45;throwState.x=e.clientX;throwState.y=e.clientY;throwState.t=now},true);C.addEventListener('pointerup',()=>{if(!throwState)return;rotV+=Math.max(-.085,Math.min(.085,throwState.vx*.055));tiltV+=Math.max(-.03,Math.min(.03,throwState.vy*.018));throwState=null},true);C.addEventListener('pointercancel',()=>throwState=null,true);
const hint=document.querySelector('.hint');if(hint)hint.textContent='1 dedo: orbitar · pellizca para navegar · suelta para cambiar de escala';const oldReset=resetUniverse;resetUniverse=function(){oldReset();expanded.clear();renderSidebarV2();clearTaskEditor()};
})();